#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check if the terminal is available
if [ -t 1 ]; then
  exec < /dev/tty && npx git-cz --hook || true
else
  echo "Terminal not available. Skipping interactive commit."
fi
